printWidth: 120
tabWidth: 2
semi: true
trailingComma: 'es5'
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
arrowParens: 'always'
parser: 'typescript'
endOfLine: 'lf'
embeddedLanguageFormatting: 'off'
