extends:
  - stylelint-config-standard
  - stylelint-config-idiomatic-order
  - stylelint-config-prettier
  - stylelint-config-recommended-scss
overrides:
  - files:
      - "src/**/*.{ts,tsx}"
    customSyntax: '@stylelint/postcss-css-in-js'
    rules: {
      'function-no-unknown': null
    }
rules:
  string-quotes: single
